[project]
name = "viscoelasticity"
version = "0.1.0"
description = "Tutorial Machine Learning in Solid Mechanics"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "klax==0.1.3",
    "matplotlib>=3.10.6",
]
